// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhczvusibhuvuvgwoezb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoY3p2dXNpYmh1dnV2Z3dvZXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODQyNDMsImV4cCI6MjA2Njk2MDI0M30.M073euHkdpLM9xlYfT3tSui_0TRXB1mq3JjYiF8dH20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});